public enum NET_FW_RULE_CATEGORY
{
    NET_FW_RULE_CATEGORY_BOOT = 0,
    NET_FW_RULE_CATEGORY_STEALTH = 1,
    NET_FW_RULE_CATEGORY_FIREWALL = 2,
    NET_FW_RULE_CATEGORY_CONSEC = 3,
    NET_FW_RULE_CATEGORY_MAX = 4
}